spring:
  datasource:
    url: ${DEV_DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PW}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  kafka:
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false
server:
  port: 8080

jwt:
  secretKey: ${JWT_SECRETKEY}

kakao:
  redirect-url: ${KAKAO_REDIRECT_URL}
  openkey-url: ${KAKAO_OPENKEY_URL}
  token-url: ${KAKAO_TOKEN_URL}
  rest-api-key: ${REST_API_KEY}
  iss: ${KAKAO_ISS}

kafka:
  broker: ${KAFKA_BROKER}